services:
  frontend:
    build:
      context: ./cb_app
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${PORT:-5169}:${PORT:-5173}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./cb_app:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./cb_app_backend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./cb_app_backend:/app
