name: DEPLOY TO SERVER

# Trigger this workflow on push or pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Use SSH to connect to the server and pull latest changes for production
      - name: Deploy to production
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.SSH_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            # Use docker-compose to build and start the application
            # NODE_ENV=production docker-compose up --build -d
            # docker-compose up
          EOF
