name: CI/CD Pipeline

# Trigger this workflow on push or pull request events
on:
  # When there is a push to the 'development' or 'main' branches
  # push:
  #   branches: [development, main]
  # When a pull request is opened, synchronized, or reopened against 'development' or 'main' branches
  pull_request:
    branches: [development, main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v2

      # Step 2: Install dependencies for cb_app_backend
      # Install dependencies for cb_app_backend
      - name: Install cb_app_backend dependencies
        working-directory: ./cb_app_backend
        run: npm install

      # Install dependencies for cb_app
      - name: Install cb_app dependencies
        working-directory: ./cb_app
        run: npm install
        # Run the test script defined in package.json
        # npm test
      # Step 4: Run Tests

  # Job to deploy to staging environment
  deploy-staging:
    # This job depends on the successful completion of the 'test' job
    needs: install
    # This job will only run if the push or pull request is to the 'development' branch
    if: github.ref == 'refs/heads/development'
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Deploy to staging environment
      # Run start:dev in cb_app_backend directory
      - name: Start backend in development mode
        working-directory: ./cb_app_backend
        run: npm run start:dev

      # Run dev in cb_app directory
      - name: Start frontend in development mode
        working-directory: ./cb_app
        run: npm run dev

  # Job to deploy to production environment
  deploy-production:
    # This job depends on the successful completion of the 'test' job
    needs: install
    # This job will only run if the push or pull request is to the 'main' branch
    if: github.ref == 'refs/heads/main'
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    # Step 1: Check out the code from the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run backend in production environment
      - name: Start backend in production
        working-directory: ./cb_app_backend
        run: npm run start:prod

      # Step 3: Run frontend in production environment
      - name: Start frontend in production
        working-directory: ./cb_app
        run: npm run dev
