name: DEPLOY TO SERVER

# Trigger this workflow on push or pull request events
on:
  push:
    branches: [main]
  pull_request:
    branches: [development, main]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job to deploy to production environment

  deploy-cb-app-backend:
    runs-on: ubuntu-latest
    # needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Use SSH to connect to the server and pull latest changes for production
      - name: Deploy backend to production
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect and deploy backend
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.SSH_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            cd cb_app_backend
            npm install
            lsof -ti:5180 | xargs kill -9 || true
            npm run start:dev
          EOF

  deploy-cb-app-frontend:
    runs-on: ubuntu-latest
    # needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Use SSH to connect to the server and pull latest changes for production
      - name: Deploy frontend to production
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect and deploy frontend
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.SSH_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            cd cb_app
            npm install
            lsof -ti:5173 | xargs kill -9 || true
            npm run dev
          EOF
